### ISSUE TITLE
what is the special client ID?

### ISSUE THREAD

**Issue by kamil-malinski** [nitanmarcel/sydney-telegram#1]
Hi!

I installed your bot and set up everything in the config-file. But I have no idea what I need to set the SYDNEY_CLIENT_ID to. I noticed that this ID is being used for the login. Where to get the ID from?

Kamil

**Comment by nitanmarcel** [comment]
It's the client ID used by the bing android application to verify that the request comes from their app.

Unfortunately It isn't supposed to be public so I can't share it.

**Comment by nitanmarcel** [comment]
Unfortunately It isn't supposed to be public so I can't share it. It must be extracted either from the app or the http2 trafic

**Comment by kamil-malinski** [comment]
could you give me a hint where to find it? I downloaded the apk and opened it in APK Editor Studio, but I have no idea where to look for it

**Comment by nitanmarcel** [comment]
> could you give me a hint where to find it? I downloaded the apk and opened it in APK Editor Studio, but I have no idea where to look for it

Sorry, but I have to be very careful with this :)
