### ISSUE TITLE
can't get suggestions to work

### ISSUE THREAD

**Issue by kamil-malinski** [nitanmarcel/sydney-telegram#2]
Hi!

I can't get suggestions to work. I'm pretty sure I have the correct SUGGESTIONS_API_KEY in my config-file but the bot never shows any suggestions with his replies. Do I have to turn them on somehow?

Cheers

Kamil

**Comment by nitanmarcel** [comment]
> Hi!
> 
> I can't get suggestions to work. I'm pretty sure I have the correct SUGGESTIONS_API_KEY in my config-file but the bot never shows any suggestions with his replies. Do I have to turn them on somehow?
> 
> Cheers
> Kamil

They work fine here, check the key again, maybe you omited something :)

**Comment by kamil-malinski** [comment]
is it enough to restart the python-script after changing the key or does the key get cached somewhere?

**Comment by nitanmarcel** [comment]
> is it enough to restart the python-script after changing the key or does the key get cached somewhere?

Just restart it

**Comment by nitanmarcel** [comment]
If you are sure is the correct key, go to this url in a browser https://www.bingapis.com/api/v7/suggestions?appid=SUGGESTIONS_API_KEY&etmkt=en-US&q=hell&lang=en-US,en;q=0.9

Replace the key with your key

**Comment by kamil-malinski** [comment]
> If you are sure is the correct key, go to this url in a browser https://www.bingapis.com/api/v7/suggestions?appid=SUGGESTIONS_API_KEY&etmkt=en-US&q=hell&lang=en-US,en;q=0.9
> 
> Replace the key with your key

I tried that and I get suggestions with my key... but the bot doesn't show them

**Comment by nitanmarcel** [comment]
> > If you are sure is the correct key, go to this url in a browser https://www.bingapis.com/api/v7/suggestions?appid=SUGGESTIONS_API_KEY&etmkt=en-US&q=hell&lang=en-US,en;q=0.9
> > Replace the key with your key
> 
> I tried that and I get suggestions with my key... but the bot doesn't show them

Have you typed something inline for the bot to show suggestions?

**Comment by kamil-malinski** [comment]
I tried many different things and never got any suggestions

I'm out of ideas, maybe I have the wrong key after all and the response I get from the api is different than your code expects, no idea

**Comment by whatthejames** [comment]
> Hi!
> 
> I can't get suggestions to work. I'm pretty sure I have the correct SUGGESTIONS_API_KEY in my config-file but the bot never shows any suggestions with his replies. Do I have to turn them on somehow?
> 
> Cheers
> 
> Kamil

Bro i can't even get Sydney client id... Help me.

**Comment by nitanmarcel** [comment]
Closed for inactivity. I hope in the end you found why the suggestions are not working
