### ISSUE TITLE
can't even get Sydney client id getting tutorial 

### ISSUE THREAD

**Issue by whatthejames** [nitanmarcel/sydney-telegram#3]
Bro i can't even get Sydney client id... Help me

**Comment by whatthejames** [comment]
Ok

**Comment by nitanmarcel** [comment]
If you can't login into the bot just forward the url with the bot after logging in into your account. To obtain the client I'd I can't help you with it.

**Comment by whatthejames** [comment]
> If you can't login into the bot just forward the url with the bot after logging in into your account. To obtain the client I'd I can't help you with it.

Can i email you for support please?
