### ISSUE TITLE
Need Simplified Version of the code 

### ISSUE THREAD

**Issue by Yorddyyorddy** [nitanmarcel/sydney-telegram#4]
some required modules are causing error while installing dependencies
like cryptg , geno ,uvloop on termux ,so please create stable version tree which that not include databse ,encyption ,authentication ,just to use with own obtained cookie file

and as you are hiding how to get client Id and client secret for Auth ,please consider to let us pass our own cookie file as json rather than login

**Comment by nitanmarcel** [comment]
Uvloop and cryptg are used to improve the speed of the bot since it is already a but slow on Sydney side. 

Anyway, in general I haven't made the not with hosting in mind for the end user and the only reason is open source is due to it requiring to use other's Microsoft account.

**Comment by Yorddyyorddy** [comment]
but it is required i think , not optional

thanks but i want to use bing chat on my terminal can you help with that , bc telegram is not accessable on our country due to govt issue

**Comment by nitanmarcel** [comment]
> but it is required i think , not optional
> 
> thanks but i want to use bing chat on my terminal can you help with that , bc telegram is not accessable on our country due to govt issue

there should be other projects for that. just search sydney using github's search function

**Comment by Yorddyyorddy** [comment]
> > but it is required i think , not optional
> > thanks but i want to use bing chat on my terminal can you help with that , bc telegram is not accessable on our country due to govt issue
> 
> there should be other projects for that. just search sydney using github's search function

there are a lot with the name but they all are outdated
